### ISSUE TITLE
运行时出现错误

### ISSUE THREAD

**Issue by YuzhenQin** [ouuan/luogu-motaki-plan-editor#1]
rt

**Comment by YuzhenQin** [comment]
运行成功后出现
```
TypeError: bindings.CanvasRenderingContext2dInit is not a function
    at node_modules/.pnpm/canvas@2.8.0/node_modules/[4mcanvas[24m/lib/context2d.js (C:\Users\zpmc\AppData\Roaming\npm\node_modules\[4mluogu-motaki-plan-editor[24m\dist\index.js:2440:14)
    at __require (C:\Users\zpmc\AppData\Roaming\npm\node_modules\[4mluogu-motaki-plan-editor[24m\dist\index.js:13:50)
    at node_modules/.pnpm/canvas@2.8.0/node_modules/[4mcanvas[24m/lib/canvas.js (C:\Users\zpmc\AppData\Roaming\npm\node_modules\[4mluogu-motaki-plan-editor[24m\dist\index.js:2556:21)
    at __require (C:\Users\zpmc\AppData\Roaming\npm\node_modules\[4mluogu-motaki-plan-editor[24m\dist\index.js:13:50)
    at node_modules/.pnpm/canvas@2.8.0/node_modules/[4mcanvas[24m/index.js (C:\Users\zpmc\AppData\Roaming\npm\node_modules\[4mluogu-motaki-plan-editor[24m\dist\index.js:3040:18)
    at __require (C:\Users\zpmc\AppData\Roaming\npm\node_modules\[4mluogu-motaki-plan-editor[24m\dist\index.js:13:50)
    at Object.<anonymous> (C:\Users\zpmc\AppData\Roaming\npm\node_modules\[4mluogu-motaki-plan-editor[24m\dist\index.js:3112:29)
[90m    at Module._compile (node:internal/modules/cjs/loader:1101:14)[39m
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:981:32)[39m
```

**Comment by ouuan** [comment]
> TypeError: bindings.CanvasRenderingContext2dInit is not a function

这个问题我在 Windows 上也遇到了，不知道如何解决。在我的 Arch Linux 上没有这个问题。

**Comment by YuzhenQin** [comment]
我在CentOS上同样遇到此情况

> > TypeError: bindings.CanvasRenderingContext2dInit is not a function
> 
> 这个问题我在 Windows 上也遇到了，不知道如何解决。在我的 Arch Linux 上没有这个问题。

**Comment by YuzhenQin** [comment]
我发给您bmp，您帮我转换成plan可以吗，谢谢

**Comment by YuzhenQin** [comment]
[导出.zip](https://github.com/ouuan/luogu-motaki-plan-editor/files/7796596/default.zip)

**Comment by ouuan** [comment]
> 我发给您bmp，您帮我转换成plan可以吗，谢谢

坐标，大小？
